branch-defaults:
  default:
    environment: imdb-actor-network-visualiser
    group_suffix: null
global:
  application_name: ImdbActorNetworkVisualiser
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
